name: Voyager Data

on:
  schedule:
    - cron:  '9 1 9 * *'
  workflow_dispatch:

jobs:
  edit:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r ./requirements.txt
      - run: python ./voyager-data.py